server:
  port: 8181
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
#      routes:
#        - id: provider_route
#          uri: http://localhost:8083
#          predicates:
#            - Path=/provider/**
#          filters:
#            - StripPrefix=1
